import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { SafePipe, CapitalizePipe } from '@src/app/core';

import {
    AvatarComponent,
    AvatarSelectorComponent,
    BadgeComponent,
    ButtonComponent,
    CountrySelectorComponent,
    FooterComponent,
    InputComponent,
    ModeSelectorComponent,
    PasswordComponent,
    PostComponent,
    SearchResultComponent,
    SearchComponent,
    SocialResultComponent,
    StatusComponent,
    StoryComponent,
    TagComponent,
} from '@src/app/shared/components';

import { StoriesComponent } from '@src/app/shared/sections';

@NgModule({
    imports: [CommonModule, FormsModule, ReactiveFormsModule, RouterModule.forChild([])],
    exports: [
        AvatarComponent,
        AvatarSelectorComponent,
        BadgeComponent,
        ButtonComponent,
        CountrySelectorComponent,
        FooterComponent,
        InputComponent,
        ModeSelectorComponent,
        PasswordComponent,
        PostComponent,
        SearchResultComponent,
        SearchComponent,
        SocialResultComponent,
        StatusComponent,
        StoryComponent,
        StoriesComponent,
        TagComponent,
    ],
    providers: [
        AvatarComponent,
        AvatarSelectorComponent,
        BadgeComponent,
        ButtonComponent,
        CountrySelectorComponent,
        FooterComponent,
        InputComponent,
        ModeSelectorComponent,
        PasswordComponent,
        PostComponent,
        SearchResultComponent,
        SearchComponent,
        SocialResultComponent,
        StatusComponent,
        StoryComponent,
        StoriesComponent,
        TagComponent,
    ],
    declarations: [
        AvatarComponent,
        AvatarSelectorComponent,
        BadgeComponent,
        ButtonComponent,
        CountrySelectorComponent,
        FooterComponent,
        InputComponent,
        ModeSelectorComponent,
        PasswordComponent,
        PostComponent,
        SearchResultComponent,
        SearchComponent,
        SocialResultComponent,
        StatusComponent,
        StoryComponent,
        StoriesComponent,
        TagComponent,
        SafePipe,
        CapitalizePipe,
    ],
})
export class SharedModule {}
